services:
  db:
    image: postgres:14.13
    environment:
      - POSTGRES_USER=blog
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=blogDB
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
    pgdata: